#[cfg(any(feature = "trace", feature = "os"))]
use chrono::DateTime;
#[cfg(any(feature = "trace", feature = "os"))]
use chrono::Local;
#[cfg(feature = "trace")]
use crossbeam::channel::Receiver;
#[cfg(feature = "trace")]
use crossbeam::channel::Sender;
#[cfg(feature = "trace")]
use pnet::datalink::MacAddr;
#[cfg(any(feature = "trace", feature = "os"))]
use pnet::packet::ethernet::EtherTypes;
#[cfg(any(feature = "trace", feature = "os"))]
use prettytable::Cell;
#[cfg(any(feature = "trace", feature = "os"))]
use prettytable::Row;
#[cfg(any(feature = "trace", feature = "os"))]
use prettytable::Table;
#[cfg(any(feature = "trace", feature = "os"))]
use prettytable::row;
/// Code obtained by analyzing the traffic generated by the Linux `traceroute` command.
#[cfg(any(feature = "trace", feature = "os"))]
use rand::RngExt;
#[cfg(any(feature = "trace", feature = "os"))]
use std::fmt;
#[cfg(any(feature = "trace", feature = "os"))]
use std::net::IpAddr;
#[cfg(any(feature = "trace", feature = "os"))]
use std::net::Ipv4Addr;
#[cfg(any(feature = "trace", feature = "os"))]
use std::net::Ipv6Addr;
use std::thread::sleep;
#[cfg(any(feature = "trace", feature = "os"))]
use std::time::Duration;
#[cfg(feature = "trace")]
use std::time::Instant;
#[cfg(any(feature = "trace", feature = "os"))]
use tracing::debug;
#[cfg(any(feature = "trace", feature = "os"))]
use tracing::error;

#[cfg(feature = "trace")]
use crate::NetInfo;
#[cfg(feature = "trace")]
use crate::RRequest;
#[cfg(feature = "trace")]
use crate::RResponse;
#[cfg(feature = "trace")]
use crate::SRequest;
#[cfg(any(feature = "trace", feature = "os"))]
use crate::error::PistolError;
#[cfg(feature = "trace")]
use crate::utils::random_port_range;
#[cfg(feature = "trace")]
use crate::utils::random_request_id;
#[cfg(feature = "trace")]
use crate::utils::time_to_string;

#[cfg(any(feature = "trace", feature = "os"))]
pub mod icmp;
#[cfg(any(feature = "trace", feature = "os"))]
pub mod icmpv6;
#[cfg(any(feature = "trace", feature = "os"))]
pub mod tcp;
#[cfg(any(feature = "trace", feature = "os"))]
pub mod tcp6;
#[cfg(any(feature = "trace", feature = "os"))]
pub mod udp;
#[cfg(any(feature = "trace", feature = "os"))]
pub mod udp6;

#[cfg(any(feature = "trace", feature = "os"))]
#[cfg(feature = "trace")]
const START_PORT: u16 = 33434;

#[cfg(any(feature = "trace", feature = "os"))]
#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HopStatus {
    TimeExceeded(IpAddr),
    NoResponse,
    Unreachable(IpAddr),
    RecvReply(IpAddr),
}

#[cfg(any(feature = "trace", feature = "os"))]
#[derive(Debug, Clone, Copy)]
pub struct Trace {
    pub addr: IpAddr,
    pub hops: u8,
    pub layer3_cost: Duration,
    pub layer2_cost: Duration,
    pub start_time: DateTime<Local>,
    pub finish_time: DateTime<Local>,
}

#[cfg(feature = "ping")]
impl fmt::Display for Trace {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut table = Table::new();
        table.add_row(Row::new(vec![
            Cell::new("Trace").style_spec("c").with_hspan(3),
        ]));

        table.add_row(row![
            c -> "addr",
            c -> "hops",
            c -> "cost"
        ]);

        let addr_str = format!("{}", self.addr);
        let hops_str = format!("{}", self.hops);
        let rtt_str = time_to_string(self.layer3_cost);
        table.add_row(row![c -> addr_str, c -> hops_str, c -> rtt_str]);

        let summary1 = format!(
            "start at: {}, finish at: {}",
            self.start_time.format("%Y-%m-%d %H:%M:%S"),
            self.finish_time.format("%Y-%m-%d %H:%M:%S"),
        );
        let layer2_cost = self.layer2_cost.as_secs_f32();
        let summary2 = format!("layer2 cost: {:.2}s", layer2_cost);
        let summary = format!("{}\n{}", summary1, summary2);
        table.add_row(Row::new(vec![Cell::new(&summary).with_hspan(3)]));
        write!(f, "{}", table)
    }
}

impl Trace {
    pub(crate) fn new(addr: IpAddr) -> Self {
        let now = Local::now();
        Trace {
            addr,
            hops: 0,
            layer3_cost: Duration::ZERO,
            layer2_cost: Duration::ZERO,
            start_time: now,
            finish_time: now,
        }
    }
    pub(crate) fn finish(&mut self, hops: u8, layer3_cost: Duration) {
        self.hops = hops;
        self.layer3_cost = layer3_cost;
        self.finish_time = Local::now();
    }
}

const TRACE_MAX_RETRY: u8 = 3;
const TRACE_RETRY_INTERVAL: f32 = 0.5;
const TRACE_MAX_HOPS: u8 = 30;

fn syn_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    dst_port: u16,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id: u16 = rng.random();
    // ensure that this u16 does not overflow
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=TRACE_MAX_HOPS {
        let random_src_port = random_port_range(1000, 65535);
        let (buff, filters) =
            tcp::build_syn_trace_packet(dst_ipv4, dst_port, src_ipv4, random_src_port, ip_id, ttl)?;

        let rrq_id = random_request_id();
        for _ in 0..TRACE_MAX_RETRY {
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv4,
                retransmit: 1,
            };

            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    // The timeout error, means no response for this ttl, continue to next ttl.
                    debug!("ipv4 syn trace recv timeout for ttl: {}", ttl);
                    // wait for a while before retrying
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };
            let hop_status = tcp::parse_syn_trace_response(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    // route returned packet
                    last_response_ttl = ttl;
                    // break the retry loop
                    break;
                }
                HopStatus::RecvReply(_) => {
                    // tcp rst packet, means packet arrive the target machine
                    debug!(
                        "ttl: {}, {:?} - {:.2}s",
                        ttl,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    trace.finish(ttl, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break, // if any response has received, break the retry loop, and continue to next ttl.
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn syn_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    dst_port: u16,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv6.into());
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=TRACE_MAX_HOPS {
        let random_src_port = random_port_range(1000, 65535);
        let (buff, filters) =
            tcp6::build_syn_trace_packet(dst_ipv6, dst_port, src_ipv6, random_src_port, hop_limit)?;

        let rrq_id = random_request_id();
        for _ in 0..TRACE_MAX_RETRY {
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv6,
                retransmit: 1,
            };
            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    debug!("ipv6 syn trace recv timeout for hop limit: {}", hop_limit);
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };
            let hop_status = tcp6::parse_syn_trace_response(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    last_response_hop_limit = hop_limit;
                    break;
                }
                HopStatus::RecvReply(_addr) => {
                    debug!(
                        "hop_limit: {}, {:?} - {:.2}s",
                        hop_limit,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    // tcp rst packet, means packet arrive the target machine
                    trace.finish(hop_limit, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break,
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

/// The default target port is 80 if not specified.
#[cfg(feature = "trace")]
pub fn syn_trace(
    net_info: NetInfo,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let dst_port = if net_info.dst_ports.len() > 0 {
        net_info.dst_ports[0]
    } else {
        // The default port is 80 if not specified, which is the same as nmap.
        80
    };
    let src_mac = net_info.inferred_src_mac;

    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match net_info.inferred_src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch {
                        addr: net_info.inferred_src_addr,
                    });
                }
            };
            let interface_name = net_info.interface_name.clone();
            syn_trace_ipv4(
                dst_mac,
                dst_ipv4,
                dst_port,
                src_mac,
                src_ipv4,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match net_info.inferred_src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch {
                        addr: net_info.inferred_src_addr,
                    });
                }
            };
            let interface_name = net_info.interface_name.clone();
            syn_trace_ipv6(
                dst_mac,
                dst_ipv6,
                dst_port,
                src_mac,
                src_ipv6,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
    }
}

fn icmp_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id = rng.random();
    let icmp_id: u16 = rng.random();
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30;
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=TRACE_MAX_HOPS {
        let (buff, filters) =
            icmp::send_icmp_trace_packet(dst_ipv4, src_ipv4, ip_id, ttl, icmp_id, ttl as u16)?;

        let rrq_id = random_request_id();
        for _ in 0..TRACE_MAX_RETRY {
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv4,
                retransmit: 1,
            };
            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    debug!("icmp trace recv timeout for ttl: {}", ttl);
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };

            let hop_status = icmp::parse_icmp_trace_response(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    last_response_ttl = ttl;
                    break;
                }
                HopStatus::RecvReply(_addr) => {
                    // recv echo reply, means packet arrive the target machine
                    debug!(
                        "ttl: {}, {:?} - {:.2}s",
                        ttl,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    trace.finish(ttl, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break,
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn icmp_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv6.into());
    let mut rng = rand::rng();
    let icmp_id: u16 = rng.random();
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=TRACE_MAX_HOPS {
        let (buff, filters) = icmpv6::build_icmpv6_trace_packet(
            dst_ipv6,
            src_ipv6,
            hop_limit,
            icmp_id,
            hop_limit as u16,
        )?;

        let rrq_id = random_request_id();
        for i in 0..TRACE_MAX_RETRY {
            debug!(
                "icmpv6 trace retry {}/{} for hop limit: {}",
                i, TRACE_MAX_RETRY, hop_limit
            );
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv6,
                retransmit: 1,
            };
            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    debug!("ipv6 icmp trace recv timeout for hop limit: {}", hop_limit);
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };

            let hop_status = icmpv6::parse_icmpv6_trace_response(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    last_response_hop_limit = hop_limit;
                    break;
                }
                // recv echo reply, means packet arrive the target machine
                HopStatus::RecvReply(_addr) => {
                    debug!(
                        "hop_limit: {}, {:?} - {:.2}s",
                        hop_limit,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    trace.finish(hop_limit, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break,
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

#[cfg(any(feature = "trace", feature = "os"))]
pub fn icmp_trace(
    net_info: NetInfo,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let src_mac = net_info.inferred_src_mac;
    let src_addr = net_info.inferred_src_addr;
    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let interface_name = net_info.interface_name.clone();
            icmp_trace_ipv4(
                dst_mac,
                dst_ipv4,
                src_mac,
                src_ipv4,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let interface_name = net_info.interface_name.clone();
            icmp_trace_ipv6(
                dst_mac,
                dst_ipv6,
                src_mac,
                src_ipv6,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
    }
}

fn udp_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id: u16 = rng.random();
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30;
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=30 {
        let random_src_port = random_port_range(1000, 65535);
        let dst_port = START_PORT + (ttl - 1) as u16;
        let (buff, filters) =
            udp::build_udp_trace_packet(dst_ipv4, dst_port, src_ipv4, random_src_port, ip_id, ttl)?;

        let rrq_id = random_request_id();
        for _ in 0..TRACE_MAX_RETRY {
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv4,
                retransmit: 1,
            };
            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    debug!("ipv4 udp trace recv timeout for ttl: {}", ttl);
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };

            let hop_status = udp::parse_udp_trace_response(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    last_response_ttl = ttl;
                    break;
                }
                // icmpunreachable, means packet arrive the target machine
                HopStatus::RecvReply(_addr) | HopStatus::Unreachable(_addr) => {
                    debug!(
                        "ttl: {}, {:?} - {:.2}s",
                        ttl,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    trace.finish(ttl, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break,
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn udp_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    interface_name: String,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let mut trace = Trace::new(dst_ipv6.into());
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=30 {
        let random_src_port = random_port_range(1000, 65535);
        let dst_port = START_PORT + (hop_limit - 1) as u16;
        let (buff, filters) =
            udp6::build_udp_trace_packet(dst_ipv6, dst_port, src_ipv6, random_src_port, hop_limit)?;

        let rrq_id = random_request_id();
        for _ in 0..TRACE_MAX_RETRY {
            let rrq = RRequest {
                interface_name: interface_name.clone(),
                id: rrq_id,
                filters: filters.clone(),
                created: Instant::now(),
                elapsed: timeout,
            };
            let srq = SRequest {
                interface_name: interface_name.clone(),
                dst_mac,
                src_mac,
                eth_payload: buff.clone(),
                eth_type: EtherTypes::Ipv6,
                retransmit: 1,
            };
            if let Err(e) = push_rd.send(rrq) {
                error!("send trace recv msg error: {}", e);
            }
            if let Err(e) = push_sd.send(srq) {
                error!("send trace packet error: {}", e);
            }

            let recv_response = match get_response.recv_timeout(timeout) {
                Ok(r) => {
                    if r.id == rrq_id {
                        r
                    } else {
                        sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                        continue;
                    }
                }
                Err(_e) => {
                    debug!("ipv6 udp trace recv timeout for hop limit: {}", hop_limit);
                    sleep(Duration::from_secs_f32(TRACE_RETRY_INTERVAL));
                    continue;
                }
            };

            let hop_status = udp6::recv_udp_trace_packet(recv_response.data)?;
            match hop_status {
                HopStatus::TimeExceeded(_addr) => {
                    last_response_hop_limit = hop_limit;
                    break;
                }
                HopStatus::RecvReply(_addr) | HopStatus::Unreachable(_addr) => {
                    // icmp unreachable, means packet arrive the target machine
                    debug!(
                        "hop limit: {}, {:?} - {:.2}s",
                        hop_limit,
                        hop_status,
                        recv_response.rtt.as_secs_f64()
                    );
                    trace.finish(hop_limit, trace_start.elapsed());
                    return Ok(trace);
                }
                _ => break,
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

#[cfg(feature = "trace")]
pub fn udp_trace(
    net_info: NetInfo,
    timeout: Duration,
    push_rd: Sender<RRequest>,
    push_sd: Sender<SRequest>,
    get_response: Receiver<RResponse>,
) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let src_mac = net_info.inferred_src_mac;
    let src_addr = net_info.inferred_src_addr;
    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let interface_name = net_info.interface_name.clone();
            udp_trace_ipv4(
                dst_mac,
                dst_ipv4,
                src_mac,
                src_ipv4,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let interface_name = net_info.interface_name.clone();
            udp_trace_ipv6(
                dst_mac,
                dst_ipv6,
                src_mac,
                src_ipv6,
                interface_name,
                timeout,
                push_rd,
                push_sd,
                get_response,
            )
        }
    }
}
