/// Code obtained by analyzing the traffic generated by the Linux `traceroute` command.
use chrono::DateTime;
use chrono::Local;
use pnet::datalink::MacAddr;
use prettytable::Cell;
use prettytable::Row;
use prettytable::Table;
use prettytable::row;
use rand::RngExt;
use std::fmt;
use std::net::IpAddr;
use std::net::Ipv4Addr;
use std::net::Ipv6Addr;
use std::time::Duration;
use std::time::Instant;
use tracing::debug;

use crate::NetInfo;
use crate::PistolStream;
use crate::error::PistolError;
use crate::utils::random_port_range;
use crate::utils::time_to_string;

pub mod icmp;
pub mod icmpv6;
pub mod tcp;
pub mod tcp6;
pub mod udp;
pub mod udp6;

const START_PORT: u16 = 33434;

#[derive(Debug, Clone, Copy, PartialEq)]
pub enum HopStatus {
    TimeExceeded(IpAddr),
    NoResponse,
    Unreachable(IpAddr),
    RecvReply(IpAddr),
}

#[derive(Debug, Clone, Copy)]
pub struct Trace {
    pub addr: IpAddr,
    pub hops: u8,
    pub layer3_cost: Duration,
    pub layer2_cost: Duration,
    pub start_time: DateTime<Local>,
    pub finish_time: DateTime<Local>,
}

impl fmt::Display for Trace {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        let mut table = Table::new();
        table.add_row(Row::new(vec![
            Cell::new("Trace").style_spec("c").with_hspan(3),
        ]));

        table.add_row(row![
            c -> "addr",
            c -> "hops",
            c -> "cost"
        ]);

        let addr_str = format!("{}", self.addr);
        let hops_str = format!("{}", self.hops);
        let rtt_str = time_to_string(self.layer3_cost);
        table.add_row(row![c -> addr_str, c -> hops_str, c -> rtt_str]);

        let summary1 = format!(
            "start at: {}, finish at: {}",
            self.start_time.format("%Y-%m-%d %H:%M:%S"),
            self.finish_time.format("%Y-%m-%d %H:%M:%S"),
        );
        let layer2_cost = self.layer2_cost.as_secs_f32();
        let summary2 = format!("layer2 cost: {:.2}s", layer2_cost);
        let summary = format!("{}\n{}", summary1, summary2);
        table.add_row(Row::new(vec![Cell::new(&summary).with_hspan(3)]));
        write!(f, "{}", table)
    }
}

impl Trace {
    pub(crate) fn new(addr: IpAddr) -> Self {
        let now = Local::now();
        Trace {
            addr,
            hops: 0,
            layer3_cost: Duration::ZERO,
            layer2_cost: Duration::ZERO,
            start_time: now,
            finish_time: now,
        }
    }
    pub(crate) fn finish(&mut self, hops: u8, layer3_cost: Duration) {
        self.hops = hops;
        self.layer3_cost = layer3_cost;
        self.finish_time = Local::now();
    }
}

const TRACE_MAX_RETRY: u8 = 3;
const TRACE_MAX_HOPS: u8 = 30;

fn syn_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    dst_port: u16,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and ip and tcp", dst_ipv4)))?;

    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id: u16 = rng.random();
    // ensure that this u16 does not overflow
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=TRACE_MAX_HOPS {
        let random_src_port = random_port_range(1000, 65535);
        let (spp, filters) = tcp::build_syn_trace_packet(
            dst_mac,
            dst_ipv4,
            dst_port,
            src_mac,
            src_ipv4,
            random_src_port,
            if_name.clone(),
            ip_id,
            ttl,
        )?;

        for _ in 0..TRACE_MAX_RETRY {
            stream.send_packet(spp.clone())?;
            let response = stream.recv_packet(timeout)?;
            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        let hop_status = tcp::parse_syn_trace_response(r)?;
                        match hop_status {
                            HopStatus::TimeExceeded(_addr) => {
                                // route returned packet
                                last_response_ttl = ttl;
                                // break the retry loop
                                break;
                            }
                            HopStatus::RecvReply(_) => {
                                // tcp rst packet, means packet arrive the target machine
                                debug!("ttl: {}, {:?}", ttl, hop_status,);
                                trace.finish(ttl, trace_start.elapsed());
                                return Ok(trace);
                            }
                            _ => break, // if any response has received, break the retry loop, and continue to next ttl.
                        }
                    }
                }
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn syn_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    dst_port: u16,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and ip6 and tcp", dst_ipv6)))?;

    let mut trace = Trace::new(dst_ipv6.into());
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=TRACE_MAX_HOPS {
        let random_src_port = random_port_range(1000, 65535);
        let (spp, filters) = tcp6::build_syn_trace_packet(
            dst_mac,
            dst_ipv6,
            dst_port,
            src_mac,
            src_ipv6,
            random_src_port,
            if_name.clone(),
            hop_limit,
        )?;

        for _ in 0..TRACE_MAX_RETRY {
            stream.send_packet(spp.clone())?;
            let response = stream.recv_packet(timeout)?;
            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        let hop_status = tcp6::parse_syn_trace_response(r)?;
                        match hop_status {
                            HopStatus::TimeExceeded(_addr) => {
                                last_response_hop_limit = hop_limit;
                                break;
                            }
                            HopStatus::RecvReply(_addr) => {
                                debug!("hop_limit: {}, {:?}", hop_limit, hop_status,);
                                // tcp rst packet, means packet arrive the target machine
                                trace.finish(hop_limit, trace_start.elapsed());
                                return Ok(trace);
                            }
                            _ => break,
                        }
                    }
                }
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

/// The default target port is 80 if not specified.
pub fn syn_trace(net_info: NetInfo, timeout: Duration) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let dst_port = if net_info.dst_ports.len() > 0 {
        net_info.dst_ports[0]
    } else {
        // The default port is 80 if not specified, which is the same as nmap.
        80
    };
    let src_mac = net_info.inferred_src_mac;

    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match net_info.inferred_src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch {
                        addr: net_info.inferred_src_addr,
                    });
                }
            };
            let if_name = net_info.if_name.clone();
            syn_trace_ipv4(
                dst_mac, dst_ipv4, dst_port, src_mac, src_ipv4, if_name, timeout,
            )
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match net_info.inferred_src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch {
                        addr: net_info.inferred_src_addr,
                    });
                }
            };
            let if_name = net_info.if_name.clone();
            syn_trace_ipv6(
                dst_mac, dst_ipv6, dst_port, src_mac, src_ipv6, if_name, timeout,
            )
        }
    }
}

fn icmp_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and icmp", dst_ipv4)))?;

    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id = rng.random();
    let icmp_id: u16 = rng.random();
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30;
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=TRACE_MAX_HOPS {
        let (spp, filters) = icmp::send_icmp_trace_packet(
            dst_mac,
            dst_ipv4,
            src_mac,
            src_ipv4,
            if_name.clone(),
            ip_id,
            ttl,
            icmp_id,
            ttl as u16,
        )?;

        for _ in 0..TRACE_MAX_RETRY {
            stream.send_packet(spp.clone())?;

            let response = stream.recv_packet(timeout)?;

            let mut response_we_want = None;
            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        response_we_want = Some(r.clone());
                        break;
                    }
                }
            }

            if let Some(r) = response_we_want {
                let hop_status = icmp::parse_icmp_trace_response(&r)?;
                match hop_status {
                    HopStatus::TimeExceeded(_addr) => {
                        last_response_ttl = ttl;
                        break;
                    }
                    HopStatus::RecvReply(_addr) => {
                        // recv echo reply, means packet arrive the target machine
                        debug!("ttl: {}, {:?}", ttl, hop_status);
                        trace.finish(ttl, trace_start.elapsed());
                        return Ok(trace);
                    }
                    _ => break,
                }
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn icmp_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and icmp6", dst_ipv6)))?;

    let mut trace = Trace::new(dst_ipv6.into());
    let mut rng = rand::rng();
    let icmpv6_id: u16 = rng.random();
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=TRACE_MAX_HOPS {
        let (spp, filters) = icmpv6::build_icmpv6_trace_packet(
            dst_mac,
            dst_ipv6,
            src_mac,
            src_ipv6,
            if_name.clone(),
            hop_limit,
            icmpv6_id,
            hop_limit as u16,
        )?;

        for i in 0..TRACE_MAX_RETRY {
            debug!(
                "icmpv6 trace retry {}/{} for hop limit: {}",
                i, TRACE_MAX_RETRY, hop_limit
            );

            stream.send_packet(spp.clone())?;

            let response = stream.recv_packet(timeout)?;
            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        let hop_status = icmpv6::parse_icmpv6_trace_response(r)?;
                        match hop_status {
                            HopStatus::TimeExceeded(_addr) => {
                                last_response_hop_limit = hop_limit;
                                break;
                            }
                            // recv echo reply, means packet arrive the target machine
                            HopStatus::RecvReply(_addr) => {
                                debug!("hop_limit: {}, {:?}", hop_limit, hop_status,);
                                trace.finish(hop_limit, trace_start.elapsed());
                                return Ok(trace);
                            }
                            _ => break,
                        }
                    }
                }
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

pub fn icmp_trace(net_info: NetInfo, timeout: Duration) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let src_mac = net_info.inferred_src_mac;
    let src_addr = net_info.inferred_src_addr;

    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let if_name = net_info.if_name.clone();
            icmp_trace_ipv4(dst_mac, dst_ipv4, src_mac, src_ipv4, if_name, timeout)
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let if_name = net_info.if_name.clone();
            icmp_trace_ipv6(dst_mac, dst_ipv6, src_mac, src_ipv6, if_name, timeout)
        }
    }
}

fn udp_trace_ipv4(
    dst_mac: MacAddr,
    dst_ipv4: Ipv4Addr,
    src_mac: MacAddr,
    src_ipv4: Ipv4Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and ip and udp", dst_ipv4)))?;

    let mut trace = Trace::new(dst_ipv4.into());
    let mut rng = rand::rng();
    let mut ip_id: u16 = rng.random();
    if ip_id >= u16::MAX - 30 {
        ip_id -= 30;
    }
    let mut last_response_ttl = 0;
    let trace_start = Instant::now();

    for ttl in 1..=30 {
        let random_src_port = random_port_range(1000, 65535);
        let dst_port = START_PORT + (ttl - 1) as u16;
        let (spp, filters) = udp::build_udp_trace_packet(
            dst_mac,
            dst_ipv4,
            dst_port,
            src_mac,
            src_ipv4,
            random_src_port,
            if_name.clone(),
            ip_id,
            ttl,
        )?;

        for _ in 0..TRACE_MAX_RETRY {
            stream.send_packet(spp.clone())?;
            let response = stream.recv_packet(timeout)?;

            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        let hop_status = udp::parse_udp_trace_response(r)?;
                        match hop_status {
                            HopStatus::TimeExceeded(_addr) => {
                                last_response_ttl = ttl;
                                break;
                            }
                            // icmpunreachable, means packet arrive the target machine
                            HopStatus::RecvReply(_addr) | HopStatus::Unreachable(_addr) => {
                                debug!("ttl: {}, {:?}", ttl, hop_status,);
                                trace.finish(ttl, trace_start.elapsed());
                                return Ok(trace);
                            }
                            _ => break,
                        }
                    }
                }
            }
        }
        ip_id += 1;
    }
    debug!("last ttl: {}", last_response_ttl);
    trace.finish(last_response_ttl, trace_start.elapsed());
    Ok(trace)
}

fn udp_trace_ipv6(
    dst_mac: MacAddr,
    dst_ipv6: Ipv6Addr,
    src_mac: MacAddr,
    src_ipv6: Ipv6Addr,
    if_name: String,
    timeout: Duration,
) -> Result<Trace, PistolError> {
    let mut stream = PistolStream::new();
    stream.init(Some(format!("host {} and ip6 and udp", dst_ipv6)))?;

    let mut trace = Trace::new(dst_ipv6.into());
    let mut last_response_hop_limit = 0;
    let trace_start = Instant::now();

    for hop_limit in 1..=30 {
        let random_src_port = random_port_range(1000, 65535);
        let dst_port = START_PORT + (hop_limit - 1) as u16;
        let (spp, filters) = udp6::build_udp_trace_packet(
            dst_mac,
            dst_ipv6,
            dst_port,
            src_mac,
            src_ipv6,
            random_src_port,
            if_name.clone(),
            hop_limit,
        )?;

        for _ in 0..TRACE_MAX_RETRY {
            stream.send_packet(spp.clone())?;
            let response = stream.recv_packet(timeout)?;
            for r in &response {
                for f in &filters {
                    if f.check(r) {
                        let hop_status = udp6::recv_udp_trace_packet(r)?;
                        match hop_status {
                            HopStatus::TimeExceeded(_addr) => {
                                last_response_hop_limit = hop_limit;
                                break;
                            }
                            HopStatus::RecvReply(_addr) | HopStatus::Unreachable(_addr) => {
                                // icmp unreachable, means packet arrive the target machine
                                debug!("hop limit: {}, {:?}", hop_limit, hop_status,);
                                trace.finish(hop_limit, trace_start.elapsed());
                                return Ok(trace);
                            }
                            _ => break,
                        }
                    }
                }
            }
        }
    }
    debug!("last hop limit: {}", last_response_hop_limit);
    trace.finish(last_response_hop_limit, trace_start.elapsed());
    Ok(trace)
}

pub fn udp_trace(net_info: NetInfo, timeout: Duration) -> Result<Trace, PistolError> {
    let dst_mac = net_info.inferred_dst_mac;
    let dst_addr = net_info.inferred_dst_addr;
    let src_mac = net_info.inferred_src_mac;
    let src_addr = net_info.inferred_src_addr;
    match dst_addr {
        IpAddr::V4(dst_ipv4) => {
            let src_ipv4 = match src_addr {
                IpAddr::V4(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let if_name = net_info.if_name.clone();
            udp_trace_ipv4(dst_mac, dst_ipv4, src_mac, src_ipv4, if_name, timeout)
        }
        IpAddr::V6(dst_ipv6) => {
            let src_ipv6 = match src_addr {
                IpAddr::V6(src) => src,
                _ => {
                    return Err(PistolError::AttackAddressNotMatch { addr: src_addr });
                }
            };
            let if_name = net_info.if_name.clone();
            udp_trace_ipv6(dst_mac, dst_ipv6, src_mac, src_ipv6, if_name, timeout)
        }
    }
}
